### ISSUE TITLE
List Index out of Range while training the model on KITTI-MOT dataset

### ISSUE THREAD

**Issue by amoghskanda** [OPEN-AIR-SUN/mars#136]
Hey, I was training the model on KITTI dataset and made the necessary path changes in the config file for the latents. When I try running the code, I get a List Index out of Range error(Line 615, mars_kitti_dataparser.py). I setup everything following the documentation including the file structure for the dataset. Any idea what could've gone wrong? I made no changes to the files except the cicai_configs file.

Traceback (most recent call last):
  File "/usr/local/bin/ns-train", line 8, in <module>
    sys.exit(entrypoint())
  File "/usr/local/lib/python3.8/dist-packages/nerfstudio/scripts/train.py", line 262, in entrypoint
    main(
  File "/usr/local/lib/python3.8/dist-packages/nerfstudio/scripts/train.py", line 247, in main
    launch(
  File "/usr/local/lib/python3.8/dist-packages/nerfstudio/scripts/train.py", line 189, in launch
    main_func(local_rank=0, world_size=world_size, config=config)
  File "/usr/local/lib/python3.8/dist-packages/nerfstudio/scripts/train.py", line 99, in train_loop
    trainer.setup()
  File "/usr/local/lib/python3.8/dist-packages/nerfstudio/engine/trainer.py", line 147, in setup
    self.pipeline = self.config.pipeline.setup(
  File "/usr/local/lib/python3.8/dist-packages/nerfstudio/configs/base_config.py", line 54, in setup
    return self._target(self, **kwargs)
  File "/app/mars/mars/mars_pipeline.py", line 81, in __init__
    self.datamanager: MarsDataManager = config.datamanager.setup(
  File "/usr/local/lib/python3.8/dist-packages/nerfstudio/configs/base_config.py", line 54, in setup
    return self._target(self, **kwargs)
  File "/usr/local/lib/python3.8/dist-packages/nerfstudio/data/datamanagers/base_datamanager.py", line 403, in __init__
    self.train_dataparser_outputs: DataparserOutputs = self.dataparser.get_dataparser_outputs(split="train")
  File "/usr/local/lib/python3.8/dist-packages/nerfstudio/data/dataparsers/base_dataparser.py", line 165, in get_dataparser_outputs
    dataparser_outputs = self._generate_dataparser_outputs(split, **kwargs)
  File "/app/mars/mars/data/mars_kitti_dataparser.py", line 1034, in _generate_dataparser_outputs
    image_filenames, depth_name, semantic_name = get_scene_images_tracking(
  File "/app/mars/mars/data/mars_kitti_dataparser.py", line 615, in get_scene_images_tracking
    frame = sorted(os.listdir(frame_dir))[frame_no]
IndexError: list index out of range

Thanks.

**Comment by yuzhongruicn** [comment]
hi! I met the same issue, how did you fix it? Thank you!

**Comment by amoghskanda** [comment]
hey. I had downloaded the dataset on windows and wanted to train the model on another system connected remotely via ssh. I had used scp to transfer files and all the files had not been transferred. Check if you have downloaded everything correctly.
