### ISSUE TITLE
overflow error when training the model

### ISSUE THREAD

**Issue by gallenszl** [OPEN-AIR-SUN/mars#63]
Hello, I try to train the model with the recommended command, i.e.,
`ns-train nsg-kitti-car-depth-recon --data /data/kitti-MOT/training/image_02/0006`
After 100000 iteration, I met such error when evaluation the model
do you have any idea about such crash？
```
Step (% Done)       Train Iter (time)    ETA (time)           Train Rays / Sec       
-----------------------------------------------------------------------------------  
400 (0.07%)         182.675 ms           1 d, 6 h, 25 m, 31 s 22.47 K                
Step (% Done)       Train Iter (time)    ETA (time)           Train Rays / Sec     Test Rays / Sec       
-------------------------------------------------------------------------------------------------------- 
99900 (16.65%)      182.364 ms           1 d, 1 h, 20 m, 0 s  22.50 K                                    
99910 (16.65%)      184.116 ms           1 d, 1 h, 34 m, 34 s 22.28 K                                    
99920 (16.65%)      181.103 ms           1 d, 1 h, 9 m, 26 s  22.67 K                                    
99930 (16.66%)      179.064 ms           1 d, 0 h, 52 m, 24 s 22.91 K                                    
99940 (16.66%)      181.108 ms           1 d, 1 h, 9 m, 24 s  22.64 K                                    
99950 (16.66%)      179.980 ms           1 d, 0 h, 59 m, 58 s 22.78 K                                    
99960 (16.66%)      177.797 ms           1 d, 0 h, 41 m, 45 s 23.06 K                                    
99970 (16.66%)      180.188 ms           1 d, 1 h, 1 m, 39 s  22.80 K                                    ureWarning: Importing `spectral_angle_mapper` from `torchmetrics.fun
99980 (16.66%)      181.691 ms           1 d, 1 h, 14 m, 9 s  22.62 K                                    ge` instead.
99990 (16.66%)      179.317 ms           1 d, 0 h, 54 m, 20 s 22.88 K                                    
Evaluating all eval images... ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╺━━━━━━━━━━ 0:04:22 72/98../aten/src/ATen/native/cuda/IndexKernel.cu:92: operator(): block: [590,0,0], thread: [44,0,0] Assertion `index >= -sizes[i] && index < sizes[i] && "index out of bounds"` failed.
Printing profiling stats, from longest to shortest duration in seconds
NSGPipeline.get_average_eval_image_metrics: 315.0857            
NSGPipeline.get_eval_image_metrics_and_images: 3.0040              
Trainer.train_iteration: 0.1781              
NSGPipeline.get_train_loss_dict: 0.1157              
NSGPipeline.get_eval_loss_dict: 0.1119              
Trainer.eval_iteration: 0.0693              
Traceback (most recent call last):
  File "/home/shenzhelun/anaconda3/envs/mars/bin/ns-train", line 8, in <module>
    sys.exit(entrypoint())
  File "/data/download/code/mars/nerfstudio/nerfstudio/scripts/train.py", line 260, in entrypoint
    main(
  File "/data/download/code/mars/nerfstudio/nerfstudio/scripts/train.py", line 246, in main
    launch(
  File "/data/download/code/mars/nerfstudio/nerfstudio/scripts/train.py", line 185, in launch
    main_func(local_rank=0, world_size=world_size, config=config)
  File "/data/download/code/mars/nerfstudio/nerfstudio/scripts/train.py", line 100, in train_loop
    trainer.train()
  File "/data/download/code/mars/nerfstudio/nerfstudio/engine/trainer.py", line 277, in train
    self.eval_iteration(step)
  File "/data/download/code/mars/nerfstudio/nerfstudio/utils/decorators.py", line 70, in wrapper
    ret = func(self, *args, **kwargs)
  File "/data/download/code/mars/nerfstudio/nerfstudio/utils/profiler.py", line 91, in inner
    out = func(*args, **kwargs)
  File "/data/download/code/mars/nerfstudio/nerfstudio/engine/trainer.py", line 504, in eval_iteration
    metrics_dict = self.pipeline.get_average_eval_image_metrics(step=step)
  File "/data/download/code/mars/nerfstudio/nerfstudio/utils/profiler.py", line 91, in inner
    out = func(*args, **kwargs)
  File "/data/download/code/mars/nsg/nsg_pipeline.py", line 223, in get_average_eval_image_metrics
    outputs = self.model.get_outputs_for_camera_ray_bundle(camera_ray_bundle)
  File "/home/shenzhelun/anaconda3/envs/mars/lib/python3.8/site-packages/torch/autograd/grad_mode.py", line 27, in decorate_context
    return func(*args, **kwargs)
  File "/data/download/code/mars/nerfstudio/nerfstudio/models/base_model.py", line 178, in get_outputs_for_camera_ray_bundle
    outputs = self.forward(ray_bundle=ray_bundle)
  File "/data/download/code/mars/nerfstudio/nerfstudio/models/base_model.py", line 140, in forward
    return self.get_outputs(ray_bundle)
  File "/data/download/code/mars/nsg/models/scene_graph.py", line 511, in get_outputs
    index = id_z_vals_obj[intersection_map[mask, 0], intersection_map[mask, 1], :, :]
RuntimeError: numel: integer multiplication overflow
```

**Comment by xBeho1der** [comment]
Hi! Thanks for your reply! We haven't met this error before. You could have a check with your dataset. By the way, you can add the training script in `.vscode/launch.json` and try to debug it.

**Comment by xBeho1der** [comment]
Glad to hear that. : )

**Comment by wuzirui** [comment]
Hi, we haven't met such issue so far. Could you please try loading the checkpoint and see whether it occurs again? If it is, maybe some debug info will provide more insights, e.g. the min/max/shape of intersection_map, mask, etc.

**Comment by wuzirui** [comment]
I am closing this issue, but feel free to reopen :)
