### ISSUE TITLE
train error

### ISSUE THREAD

**Issue by baekhyun77** [OPEN-AIR-SUN/mars#91]
Hello, thank you for your work. When I was running：ns-train nsg-kitti-car-depth-recon --data /data/kitti-MOT/training/image_02/0006

 this error occurred：
 ```
WARNING: Using a slow implementation of HashEncoding. 
🏃 🏃 Install tcnn for speedups 🏃 🏃
pip install git+https://github.com/NVlabs/tiny-cuda-nn/#subdirectory=bindings/torch


WARNING: Using a slow implementation of HashEncoding. 
🏃 🏃 Install tcnn for speedups 🏃 🏃
pip install git+https://github.com/NVlabs/tiny-cuda-nn/#subdirectory=bindings/torch

Traceback (most recent call last):
  File "/root/miniconda3/envs/nerfstudio/bin/ns-train", line 5, in <module>
    from nerfstudio.scripts.train import entrypoint
  File "/root/autodl-tmp/mars/nerfstudio/nerfstudio/scripts/train.py", line 62, in <module>
    from nerfstudio.configs.method_configs import AnnotatedBaseConfigUnion
  File "/root/autodl-tmp/mars/nerfstudio/nerfstudio/configs/method_configs.py", line 594, in <module>
    external_methods, external_descriptions = discover_methods()
  File "/root/autodl-tmp/mars/nerfstudio/nerfstudio/plugins/registry.py", line 43, in discover_methods
    spec = discovered_entry_points[name].load()
  File "/root/miniconda3/envs/nerfstudio/lib/python3.8/site-packages/setuptools/_vendor/importlib_metadata/__init__.py", line 208, in load
    module = import_module(match.group('module'))
  File "/root/miniconda3/envs/nerfstudio/lib/python3.8/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "/root/autodl-tmp/mars/nsg/cicai_configs.py", line 20, in <module>
    from nsg.models.scene_graph import SceneGraphModelConfig
  File "/root/autodl-tmp/mars/nsg/models/scene_graph.py", line 66, in <module>
    from nsg.models.sky_model import SkyModelConfig
  File "/root/autodl-tmp/mars/nsg/models/sky_model.py", line 10, in <module>
    import tinycudann as tcnn
  File "/root/miniconda3/envs/nerfstudio/lib/python3.8/site-packages/tinycudann-1.7-py3.8-linux-x86_64.egg/tinycudann/__init__.py", line 9, in <module>
    from tinycudann.modules import free_temporary_memory, NetworkWithInputEncoding, Network, Encoding
  File "/root/miniconda3/envs/nerfstudio/lib/python3.8/site-packages/tinycudann-1.7-py3.8-linux-x86_64.egg/tinycudann/modules.py", line 51, in <module>
    _C = importlib.import_module(f"tinycudann_bindings._{cc}_C")
  File "/root/miniconda3/envs/nerfstudio/lib/python3.8/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
ImportError: /root/miniconda3/envs/nerfstudio/lib/python3.8/site-packages/tinycudann-1.7-py3.8-linux-x86_64.egg/tinycudann_bindings/_70_C.cpython-38-x86_64-linux-gnu.so: undefined symbol: _ZN2at4_ops19empty_memory_format4callEN3c108ArrayRefIlEENS2_8optionalINS2_10ScalarTypeEEENS5_INS2_6LayoutEEENS5_INS2_6DeviceEEENS5_IbEENS5_INS2_12MemoryFormatEEE
```
 Do you know the reason ？

**Comment by xBeho1der** [comment]
Hi! Thanks for your reply! It seems like you haven't installed [tiny-cuda-nn](https://github.com/NVlabs/tiny-cuda-nn) successfully.
